version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zion_project_manager
      MYSQL_USER: zion
      MYSQL_PASSWORD: matrix
    ports:
      - 3306:3306
