"use client";
import { Inter } from "next/font/google";
import Sidebar from "../components/molecules/Sidebar";
import { useContext } from "react";
import { authContext } from "../store/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-5/6">
      <Sidebar />
      <div className="w-full">{children}</div>
    </div>
  );
}
